

new:
  path: /new
  defaults: {_controller: "GuestBookBundle:Post:new"}

create:
  path: /create
  defaults: {_controller: "GuestBookBundle:Post:create"}
  methods: [POST]
  
delete:
  path: /{id}/delete
  defaults: {_controller: "GuestBookBundle:Post:delete"}
  methods: [POST]

show:
  path: /{id}/show
  defaults: {_controller: "GuestBookBundle:Post:show"}
  methods: [GET]
  
 