

new:
  path: /new
  defaults: {_controller: "GuestBookBundle:Post:new"}

create:
  path: /create
  defaults: {_controller: "GuestBookBundle:Post:create"}
  methods: [POST]
  
delete:
  path: /{id}/delete
  defaults: {_controller: "GuestBookBundle:Post:delete"}
  methods: [POST]
  
edit:
  path: /{id}/edit
  defaults: {_controller: "GuestBookBundle:Post:edit"}
  methods: [GET]
  
save:
  path: /{id}/save
  defaults: {_controller: "GuestBookBundle:Post:save"}

show:
  path: /{id}/show
  defaults: {_controller: "GuestBookBundle:Post:show"}
  methods: [GET]
  
 